spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  maxCar: 100
  thymeleaf:
    check-template-location: false
sort:
  enabled-fields:
    - make
    - model
    - series